# Generated by Django 3.2.5 on 2021-07-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='tg_name',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='Имя бота'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='tg_user_name',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='Telegram id бота'),
        ),
    ]
